---
aws_vpc_cidr: 172.31.0.0/16
openstack_app_cidr: 10.0.1.0/24
openstack_vpn_app_ip: 10.0.1.254

wireguard_interface: wg0
wireguard_port: 51820
wireguard_config_dir: /etc/wireguard
wireguard_private_key_path: /etc/wireguard/privatekey
wireguard_persistent_keepalive: 25

# Keep this enabled while the OpenStack app security group allows traffic via
# the VPN gateway path during testing.
wireguard_openstack_app_nat: true
