#!/usr/bin/env python3
"""
This script is used to extract active rules and export tuned exclusions (SecRuleRemoveById)
from a trained L1-regularized ML model to Nginx WAF Core Rule Set rules.
This simulates the MLOps pipeline automation after retraining.
"""

import os
import sys
import toml
import json
import joblib
import argparse

# Add parent directory to path so we can import src
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

def main():
    parser = argparse.ArgumentParser(description='Export tuned ModSecurity rules from trained ML models')
    parser.add_argument('--model', type=str, default='linear_svc_pl4_l1.joblib',
                        help='Name of the joblib model file inside data/models/')
    parser.add_argument('--threshold', type=float, default=1e-5,
                        help='Coefficient absolute threshold to consider a rule active')
    parser.add_argument('--output', type=str, default=None,
                        help='Custom path to write the exclusion conf file (e.g. specific Ansible folder)')
    
    args = parser.parse_args()
    
    # Load config settings
    if not os.path.exists('config.toml'):
        print("[ERROR] config.toml not found! Please run this script from modsec-learn root.")
        sys.exit(1)
        
    settings = toml.load('config.toml')
    crs_ids_path = settings['crs_ids_path']
    models_path = settings['models_path']
    crs_dir = settings['crs_dir']
    
    # Load the model
    model_file_path = os.path.join(models_path, args.model)
    if not os.path.exists(model_file_path):
        print(f"[ERROR] Model file {model_file_path} not found!")
        sys.exit(1)
        
    print(f"[INFO] Loading trained model: {args.model}")
    model = joblib.load(model_file_path)
    
    # Load the list of CRS SQLi Rule IDs
    if not os.path.exists(crs_ids_path):
        print(f"[ERROR] CRS IDs file {crs_ids_path} not found!")
        sys.exit(1)
        
    with open(crs_ids_path, 'r') as file:
        crs_ids = sorted(json.load(file)['rules_ids'])
        
    print(f"[INFO] Loaded {len(crs_ids)} total CRS SQLi Rule IDs.")
    
    # Extract coefficients
    if not hasattr(model, 'coef_'):
        print("[ERROR] Loaded model does not have coefficients (coef_ attribute). Please use svc or log_reg models.")
        sys.exit(1)
        
    coefs = model.coef_.flatten()
    
    if len(coefs) != len(crs_ids):
        print(f"[ERROR] Coefficients length ({len(coefs)}) does not match rule IDs count ({len(crs_ids)})!")
        sys.exit(1)
        
    # Analyze rules based on weights
    active_rules = []
    redundant_rules = []
    
    print("\n--- Model Coefficients & Rule Analysis ---")
    for rule_id, weight in zip(crs_ids, coefs):
        abs_weight = abs(weight)
        if abs_weight > args.threshold:
            active_rules.append((rule_id, weight))
            status = "KEEP (Active)"
        else:
            redundant_rules.append((rule_id, weight))
            status = "REMOVE (Zero Weight)"
            
        print(f"Rule {rule_id} | Weight: {weight:+.6f} | Status: {status}")
        
    print("\n--- Summary ---")
    print(f"Total Rules Analyzed: {len(crs_ids)}")
    print(f"Active Rules (Coefficients != 0): {len(active_rules)}")
    print(f"Redundant Rules (Coefficients == 0): {len(redundant_rules)}")
    
    # Determine output paths
    output_paths = []
    
    if args.output:
        output_paths.append(args.output)
    else:
        # 1. Output to local docker-compose CRS rules folder for local testing
        local_crs_rule_path = os.path.join(crs_dir, 'RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf')
        output_paths.append(local_crs_rule_path)
        
        # 2. Output to Ansible role files directory for WAF deployment on AWS
        ansible_role_files_dir = '../ansible/roles/nginx_waf/files'
        ansible_rule_path = os.path.join(ansible_role_files_dir, 'RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf')
        output_paths.append(ansible_rule_path)
        
    # Generate the ModSecurity exclusion file for each output path
    for file_path in output_paths:
        # Create directories if they do not exist
        parent_dir = os.path.dirname(file_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir, exist_ok=True)
            
        print(f"\n[INFO] Generating exclusion rule file at: {file_path}")
        
        with open(file_path, 'w') as file:
            file.write("# ==============================================================================\n")
            file.write("# MODSECURITY TUNED EXCLUSION RULES (AUTOMATICALLY GENERATED BY ML PIPELINE)\n")
            file.write(f"# Model used: {args.model}\n")
            file.write(f"# Threshold used: {args.threshold}\n")
            file.write(f"# Active Rules Kept: {len(active_rules)} | Redundant Rules Disabled: {len(redundant_rules)}\n")
            file.write("# ==============================================================================\n\n")
            
            file.write("# --- Active Rules Kept & Weights Info ---\n")
            for r_id, w in sorted(active_rules, key=lambda x: abs(x[1]), reverse=True):
                file.write(f"# Rule {r_id} | Feature Weight: {w:+.6f}\n")
            file.write("\n")
            
            file.write("# --- SecRuleRemoveById block for Redundant/Noisy Rules ---\n")
            if redundant_rules:
                disabled_ids_str = " ".join([r_id for r_id, _ in sorted(redundant_rules)])
                file.write(f"SecRuleRemoveById {disabled_ids_str}\n")
                file.write("# Rules successfully pruned to prevent False Positives.\n")
            else:
                file.write("# No rules were pruned.\n")
                
        print(f"[SUCCESS] Tuned rule configuration file written successfully to {file_path}")

    print("\n[MLOPS READY] Rules are ready for local docker WAF and Ansible AWS deployment!")

if __name__ == '__main__':
    main()
