---
- name: Deploy centralized PostgreSQL DB node
  hosts: db_nodes
  become: true
  gather_facts: true
  roles:
    - postgresql_centralized

- name: Deploy lightweight auth app node
  hosts: app_nodes
  become: true
  gather_facts: true
  vars:
    filebeat_node_role: app
    filebeat_inputs: "{{ filebeat_app_inputs }}"
  roles:
    - simple_auth_app
    - filebeat_agent
